### ISSUE TITLE
merge will print lot's of @Optional not set value

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_anon#16]
using tink.Anon;
	using tink.CoreApi;

	typedef DataServerListObj = {
		@:optional var from:Int;
		@:optional var to:Int;
	}

	typedef SType = {
		@:optional var infor:String;
	}

	class Main {
		function new() {}

		static public function main() {
			var obj:DataServerListObj = {from: 1};
			var st:SType = {infor: "d"};

			trace(obj);// { from: 1 } instead of   { from: 1 ,to:undefind};
			var m = obj.merge(st);

			trace(m); // I don't expected to=undefined here that I not set 
		}
	}

**Comment by back2dos** [comment]
This fixes it:

```haxe
var m:DataServerListObj & SType = obj.merge(st);
```

It's always better to use explicit type with `merge`.

**Comment by sonygod** [comment]
good !that's what I want
