### ISSUE TITLE
Add with?

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_anon#9]
@nadako dropped this gist in the haxe gitter some time ago: https://gist.github.com/nadako/7edbc859e5206b2dbd65df2fd96aa334
Seems like it could be a good fit to add something like this to tink_anon?

**Comment by back2dos** [comment]
Hmm, if you do `using tink.Anon` then `player.merge(level = player.level + 1);` will compile just fine. Or am I missing something?

**Comment by benmerckx** [comment]
Oh my bad, the docs say:
- object literals: the macro attempts to merge *all* fields of *all* object literals into one expression. If there is a **duplicate field, this will lead to an error**, e.g. `tink.Anon.merge({ foo: 12 }, { foo: 13 })` will not compile.
- `ident = expr` which is a shorthand for `{ ident: expr }` which is treated as any object literal

Which made me think it's impossible to 'change' a field, didn't even think to try :)

**Comment by benmerckx** [comment]
Right I get it now:
````haxe
var a = { foo: 12 };
tink.Anon.merge(a, { foo: 13 }); // ok
tink.Anon.merge({ foo: 12 }, { foo: 13 }); // fail
````
Not sure if I'm just stupid or the docs need clarification...

**Comment by back2dos** [comment]
Well, `{ foo: 12 }` is an object literal and `a` is not. Technically, the doc is correct, but obviously also just as useless, since you're already at least the 3rd person to misread it :D

**Comment by back2dos** [comment]
Hmm, ok, not sure how to improve the actual documentation (the third rule from the list of which you quoted the first two quite explicitly states that this will work), but I'd be more than happy to accept suggestions. In the meantime I added an example that I hope will clarify things.
